services:

  database:
    image: mysql:8.4.0
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_ROOT_USER
      - MYSQL_DATABASE
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 15
    networks:
      - vas

  liquibase:
    build:
      dockerfile: .dockerfile
    environment:
      - INSTALL_MYSQL=true
    tty: true
    stdin_open: true
    networks:
      - vas
    depends_on:
      database:
        condition: service_healthy

networks:
  vas:
    name: vas